name: Lint Shell Script

on:
  workflow_call:
  push:
    branches: [main]
    paths:
      - "**.sh"
  pull_request:
    branches: [main]
    paths:
      - "**.sh"

concurrency:
  group: lint-shell-script-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-shell-script:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Lint shell scripts
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
        with:
          scandir: .
          version: "v0.11.0"
        env:
          SHELLCHECK_OPTS: -e SC2034
